### ISSUE TITLE
Down to Help

### ISSUE THREAD

**Issue by justingolden21** [Hidden50/pq#1]
Hi Hidden50,

I was thinking of working on my own Pokemon Quest website as most of them are either super simple, or ugly, or don't have all the information. Yours is among the best I've seen, and I'd be down to help improve the aesthetic overall and maybe add some more features and improve UX. Let me know if you're interested in this. It wouldn't require any work from you; I'd just improve the website and then make a PR.

Thanks,

Justin

**Comment by Hidden50** [comment]
Hey, thanks for the offer and sorry for the late response. Any help is welcome!

It's been a while since I worked on pq dex, but I'm happy to pick it back up. I should probably finish adding recipes.
