### ISSUE TITLE
Butterfree has Venonat's image

### ISSUE THREAD

**Issue by justingolden21** [Hidden50/pq#2]
The image here:
https://hidden50.github.io/pq/faces.min.png
Has two venonat
and on the website, searching butterfree shows:
![image](https://user-images.githubusercontent.com/30274440/98900575-e90adf00-2466-11eb-920b-011a41db7b5f.png)

**Comment by Hidden50** [comment]
You mean the ones at position 4,3 and 6,7? They do indeed look similar, but I believe that's how they really look in the game. The source files that get compiled into faces.min.png can be found here:

https://github.com/Hidden50/pq/blob/master/src/faces/012.png
https://github.com/Hidden50/pq/blob/master/src/faces/048.png

**Comment by justingolden21** [comment]
Oh you're right. My mistake.
